apiVersion: opentofu.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each tofu workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
    - filename: .tofurc # use exactly this filename by convention
      source: Secret
      secretRef:
        namespace: default
        name: tofurc
        key: .tofurc
    # Example: https://marketplace.upbound.io/providers/upbound/provider-opentofu/v0.2.5/resources/opentofu.upbound.io/ProviderConfig/v1beta1
    - filename: aws-creds.ini
      secretRef:
        key: aws-creds.ini
        name: crossplane-aws-credentials
        namespace: crossplane-system
      source: Secret
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  # Should have used backend namespace = crossplay-system. TODO post-pilot.
  configuration: |
    // Modules _must_ use remote state. The provider does not persist state.
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-default"
        namespace         = "default"
        in_cluster_config = true
      }
    }
    // Configure AWS provider with credentials.
    provider "aws" {
      shared_credentials_file = "${path.module}/aws-creds.ini"
      region = "us-east-1"
    }
